name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.2

      - name: Install node
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm test

      - run: npm run build
